import Foundation

/// The hexagonal lattice the whole map is built on — the Swift port of
/// `src/hexgrid.js`.
///
/// Flat-top hexagons defined in Web Mercator space, so every cell renders as a
/// perfect, identically-oriented hexagon at any location and zoom: no rotation
/// and no pentagon artifacts. The trade of a Mercator grid is that ground size
/// shrinks with latitude (×cos φ) while on-screen size stays constant.
///
/// This file carries a requirement the rest of the port does not: it has to
/// agree with the JavaScript *exactly*. A cell id is a key the server already
/// holds rows under, so a column one out at some latitude does not draw a
/// slightly wrong map — it fails to find the map at all. The tests assert
/// against vectors generated by running the JavaScript itself, rather than
/// against numbers anyone typed.
public enum HexGrid {

    // MARK: - Constants

    public static let earthRadius = 6_378_137.0

    /// Mercator world width ≈ 40_075_017 m.
    public static let world = 2 * Double.pi * earthRadius

    /// The Web Mercator latitude clamp (±85.05°).
    public static let maxMercatorY = world / 2

    public static let sqrt3 = 3.0.squareRoot()

    public static let maxLevel = 6

    /// Columns around the globe at level 0.
    ///
    /// The `n · 3^maxLevel` form keeps the column count integer *and* even at
    /// every level, so the odd-column vertical offset wraps seamlessly at the
    /// antimeridian. n = 858 is also divisible by 6, so the level past the top
    /// stays even too. The base cell is ~74 m flat-to-flat at the equator,
    /// which is 50 m on the ground near 47°.
    public static let baseCols = 858 * 729  // 858 · 3^6 = 625_482

    /// Level-0 column spacing = 1.5 · R0.
    public static let columnSpacing0 = world / Double(baseCols)

    /// Level-0 circumradius.
    public static let radius0 = columnSpacing0 / 1.5

    // MARK: - Mercator

    public static func mercatorX(lng: Double) -> Double {
        (lng / 360) * world
    }

    public static func mercatorY(lat: Double) -> Double {
        // Clamped just short of ±1 because atanh(±1) is infinite. This is what
        // puts the poles at a finite y instead of off the edge of the world.
        let s = min(0.9999999, max(-0.9999999, sin((lat * Double.pi) / 180)))
        return earthRadius * atanh(s)
    }

    public static func longitude(x: Double) -> Double {
        (x / world) * 360
    }

    public static func latitude(y: Double) -> Double {
        (atan(sinh(y / earthRadius)) * 180) / Double.pi
    }

    // MARK: - Lattice

    /// 3^n in integers, so the column counts stay exact rather than arriving
    /// through a Double that is one ulp short of a whole number.
    private static func pow3(_ n: Int) -> Int {
        var v = 1
        for _ in 0..<n { v *= 3 }
        return v
    }

    public static func radius(level: Int) -> Double {
        radius0 * Double(pow3(level))
    }

    /// Integer and even at every level, by construction of `baseCols`.
    public static func columns(level: Int) -> Int {
        baseCols / pow3(level)
    }

    /// A positive remainder. Swift's `%` keeps the sign of the dividend, so a
    /// column just west of the antimeridian would otherwise come back negative
    /// and never match the same ground approached from the east.
    public static func normalizedColumn(_ col: Int, _ n: Int) -> Int {
        ((col % n) + n) % n
    }

    /// The Mercator centre of a cell. Flat-top, "odd-q" offset layout: odd
    /// columns shift up half a row.
    public static func cellCenter(level: Int, col: Int, row: Int) -> (x: Double, y: Double) {
        let r = radius(level: level)
        let oddColumn = (col & 1) != 0
        return (
            1.5 * r * Double(col),
            sqrt3 * r * (Double(row) + (oddColumn ? 0.5 : 0))
        )
    }

    /// JavaScript's `Math.round` rounds a half toward +∞ — `Math.round(-2.5)` is
    /// -2 — where Swift's `.rounded()` rounds a half away from zero and gives
    /// -3. Every cell id in the database was written by the JavaScript, so the
    /// port has to round the way it does. It is the only difference between the
    /// two languages here, and it shows up only exactly on a cell boundary,
    /// which is precisely where a map gets clicked.
    /// Internal rather than private so the tests can pin it directly. Reaching
    /// it through `pointToCell` looked like the tidier test and was a worse one:
    /// cube rounding corrects whichever axis moved furthest, so a point
    /// constructed to land on a half never reaches this as a half at all.
    @inline(__always)
    static func jsRound(_ v: Double) -> Double {
        (v + 0.5).rounded(.down)
    }

    /// A Mercator point to the cell containing it, via axial coordinates and
    /// cube rounding. Resolving mathematically rather than by hit-testing is
    /// what makes a tap behave the same on a boundary, in a gap, and at any
    /// zoom.
    public static func pointToCell(level: Int, x: Double, y: Double) -> (col: Int, row: Int) {
        let r = radius(level: level)
        let qf = ((2.0 / 3.0) * x) / r
        let rf = (-x / 3 + (sqrt3 / 3) * y) / r

        var q = jsRound(qf)
        var rr = jsRound(rf)
        let s = jsRound(-qf - rf)

        // Cube rounding: the three axes must sum to zero, so whichever moved
        // furthest is the one recomputed from the other two.
        let dq = abs(q - qf)
        let dr = abs(rr - rf)
        let ds = abs(s - (-qf - rf))

        if dq > dr && dq > ds {
            q = -s - rr
        } else if dr > ds {
            rr = -q - s
        }

        let col = Int(q)
        let axialRow = Int(rr)
        // axial → odd-q offset. The numerator is always even, so the integer
        // division is exact for negative columns too.
        return (col, axialRow + (col - (col & 1)) / 2)
    }

    /// The coarse cell one level up that contains this cell's centre — the
    /// roll-up that lets a single visited cell light its whole country.
    public static func parent(level: Int, col: Int, row: Int) -> (col: Int, row: Int) {
        let centre = cellCenter(level: level, col: col, row: row)
        let up = pointToCell(level: level + 1, x: centre.x, y: centre.y)
        return (normalizedColumn(up.col, columns(level: level + 1)), up.row)
    }

    // MARK: - Cell ids
    //
    // The string the server keys its rows on. It is built by `cellIdAt()` in
    // src/main.js rather than in the shared maths module, but a native client
    // that gets the format wrong finds no cells at all — so it belongs beside
    // the lattice it names.

    /// `"{level}/{column}/{row}"`, with the column wrapped into range so the
    /// same ground matches however many world copies you panned across.
    public static func cellId(level: Int, col: Int, row: Int) -> String {
        "\(level)/\(normalizedColumn(col, columns(level: level)))/\(row)"
    }

    public static func cellId(level: Int, lat: Double, lng: Double) -> String {
        let cell = pointToCell(level: level, x: mercatorX(lng: lng), y: mercatorY(lat: lat))
        return cellId(level: level, col: cell.col, row: cell.row)
    }
}
