// Autogenerated from Pigeon (v29.0.6), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>"))"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

enum NativePigeonInternal {
  static func isNullish(_ value: Any?) -> Bool {
    guard let innerValue = value else {
      return true
    }

    if case Optional<Any>.some(Optional<Any>.none) = value {
      return true
    }

    return innerValue is NSNull
  }
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}


private class NativePigeonCodecReader: FlutterStandardReader {
}

private class NativePigeonCodecWriter: FlutterStandardWriter {
}

private class NativePigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return NativePigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return NativePigeonCodecWriter(data: data)
  }
}

class NativePigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = NativePigeonCodec(readerWriter: NativePigeonCodecReaderWriter())
}


/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol SporraNative {
  func settings() throws -> String
  func configure(json: String) async throws -> String
  func sync() async throws -> String
  func signOut() async throws
  func photos() async throws -> String
  func thumbnail(index: Int64, pixels: Int64) async throws -> FlutterStandardTypedData
  func playVideo(index: Int64) async throws
  func saveImage(png: FlutterStandardTypedData) async throws
  func authenticate(url: String) async throws -> String
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class SporraNativeSetup {
  static var codec: FlutterStandardMessageCodec { NativePigeonCodec.shared }
  /// Sets up an instance of `SporraNative` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: SporraNative?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let settingsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.sporra_flutter.SporraNative.settings\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      settingsChannel.setMessageHandler { _, reply in
        do {
          let result = try api.settings()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      settingsChannel.setMessageHandler(nil)
    }
    let configureChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.sporra_flutter.SporraNative.configure\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      configureChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let jsonArg = args[0] as! String
        Task { @MainActor in
          do {
            let result = try await api.configure(json: jsonArg)
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      configureChannel.setMessageHandler(nil)
    }
    let syncChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.sporra_flutter.SporraNative.sync\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      syncChannel.setMessageHandler { _, reply in
        Task { @MainActor in
          do {
            let result = try await api.sync()
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      syncChannel.setMessageHandler(nil)
    }
    let signOutChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.sporra_flutter.SporraNative.signOut\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      signOutChannel.setMessageHandler { _, reply in
        Task { @MainActor in
          do {
            try await api.signOut()
            reply(wrapResult(nil))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      signOutChannel.setMessageHandler(nil)
    }
    let photosChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.sporra_flutter.SporraNative.photos\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      photosChannel.setMessageHandler { _, reply in
        Task { @MainActor in
          do {
            let result = try await api.photos()
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      photosChannel.setMessageHandler(nil)
    }
    let thumbnailChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.sporra_flutter.SporraNative.thumbnail\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      thumbnailChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let indexArg = args[0] as! Int64
        let pixelsArg = args[1] as! Int64
        Task { @MainActor in
          do {
            let result = try await api.thumbnail(index: indexArg, pixels: pixelsArg)
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      thumbnailChannel.setMessageHandler(nil)
    }
    let playVideoChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.sporra_flutter.SporraNative.playVideo\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      playVideoChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let indexArg = args[0] as! Int64
        Task { @MainActor in
          do {
            try await api.playVideo(index: indexArg)
            reply(wrapResult(nil))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      playVideoChannel.setMessageHandler(nil)
    }
    let saveImageChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.sporra_flutter.SporraNative.saveImage\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      saveImageChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let pngArg = args[0] as! FlutterStandardTypedData
        Task { @MainActor in
          do {
            try await api.saveImage(png: pngArg)
            reply(wrapResult(nil))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      saveImageChannel.setMessageHandler(nil)
    }
    let authenticateChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.sporra_flutter.SporraNative.authenticate\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      authenticateChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let urlArg = args[0] as! String
        Task { @MainActor in
          do {
            let result = try await api.authenticate(url: urlArg)
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      authenticateChannel.setMessageHandler(nil)
    }
  }
}
